### ISSUE TITLE
support both groups and users as `admin`

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/osc-trino-acl-dsl#6]
We have requests pertaining to specifying user-based access control, not just groups

my concept is to alter the DSL format so it looks like:
```yaml
admin:
  - user: <user name or pattern>
  - group: <group name or pattern>
  - user: <another pattern>
  - user: <and another>
  - group: <and another>
  - ...
```
