### ISSUE TITLE
unify row and column access controls in DSL

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/osc-trino-acl-dsl#8]
Proposal similar to
```
    row-column-acl:
      # "groups" will actually be list of user or group names, see #6 
      - groups: [demo_dv_quant]
        hide-columns: [dev1]
        row-filters: ["year <= 2017"]
      - groups: [demo_dv_user]
        hide-columns: [quant1]
        row-filter: ["country = 'france'"] 
```

This list will no longer be cumulative.  In the event that table defaults to `public`, the default-public rule will have union of all hidden columns, and intersection of all filters, so public unprivileged users will be guaranteed to have <= access of any user or group enumerated in the row-column-acl list.

xref: https://chat.google.com/room/AAAA9aU92zc/2IYyTijkQHA
